"""
ComfyUI WhisperX Pro - Accurate Audio Transcription and Alignment Nodes
"""

from .whisperx_srt_node import NODE_CLASS_MAPPINGS as SRT_NODE_CLASS_MAPPINGS, NODE_DISPLAY_NAME_MAPPINGS as SRT_NODE_DISPLAY_NAME_MAPPINGS

# Use only SRT node mappings
NODE_CLASS_MAPPINGS = {
    **SRT_NODE_CLASS_MAPPINGS,
}

NODE_DISPLAY_NAME_MAPPINGS = {
    **SRT_NODE_DISPLAY_NAME_MAPPINGS,
}

__all__ = ['NODE_CLASS_MAPPINGS', 'NODE_DISPLAY_NAME_MAPPINGS']